export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { Features } from './Features'
export { Testimonials } from './Testimonials'
export { FAQ } from './FAQ'
export { CTA } from './CTA'
export { Footer } from './Footer'
